### Pollinator network: data handling and visualisation


# Crucial package for today 
library(bipartite)
?bipartite

# Basic network visualisation: 
plotweb(Safariland)
# also as a matrix: 
visweb(Safariland)

# But how to get it? 

# First we have usually data in the long-format, i.e., data where one row usually represents individual observations. However, we usually need wide-format data, i.e., data where rows represent species of one partner (e.g., pollinators) and columns represents species of other partners (e.g., plants). 

# Lets see example of the format transfer on HairEyeColor dataset - instead of species we have hair and Eye colour: 


HairEye <-  data.frame(HairEyeColor) # we will do a little bit of cheating here. We will use HairEyeColor and put them to the dataframe

HairEye # This is how data usually looks like when obtained in the field

## This is often called "long" data 

## How to translate it into "wide" data?

HairEyeweb <- tapply(HairEye$Freq, list(HairEye$Hair,HairEye$Eye), sum) # simply by tapply() function, summing the frequences of occurence together

HairEyeweb

plotweb(HairEyeweb) # ploting the web


### PLOTWEB function ####


plotweb(HairEyeweb) # ploting the web


plotweb(HairEyeweb, 
        method="cca", #    Default method is cca, which leads to as few crossings of interactions as possible. The other option is normal, which leaves order as given by the matrix. 
        text.rot = 90,
        labsize =1, 
        ybig = 0.8, 
        low.y = 0.6, 
        high.y = 0.98, 
        plot.axes = FALSE, 
        y.width.low = 0.05, 
        y.width.high = 0.05, 
        low.spacing=0.01, 
        high.spacing=0.01,
        bor.col.low = "black",
        col.low = "red",
        col.high = "gray",
        bor.col.high = "black",  
        bor.col.interaction = rgb(250,250,250, alpha = 50, max=255), 
        col.interaction=rgb(0,0,0, alpha = 90, max=255))


### Lets now play more with real dataset: 
jc_net <- read.csv("jc_network21.csv")

# dataset of pollinator interactions from our study

head(jc_net)


jc_web <-  tapply(jc_net$number , list(jc_net$pollinator, jc_net$plant), sum) # 

jc_web[is.na(jc_web)] <- 0 # replace NA with 0 

plotweb(jc_web, "cca")


plotweb(jc_web, "cca", col.interaction = rgb(0,0,0, max = 255, alpha = 100),  bor.col.interaction  = rgb(0,0,0, max = 255, alpha = 100))


par(font = 3)
plotweb(t(jc_web), method="normal", text.rot = 90, labsize =1.6, ybig = 0.8, low.y = 0.6, high.y = 0.98, plot.axes = FALSE, y.width.low = 0.05, y.width.high = 0.05,  col.low = rgb(0,255,0, max = 255, alpha = 100), bor.col.interaction = rgb(0,0,0, max = 255, alpha = 100), bor.col.high= rgb(100,0,0, max = 255, alpha = 100), low.spacing=0.05, high.spacing=0.06, bor.col.low= rgb(0,255,0, max = 255, alpha = 100),
        col.interaction =rgb(0,0,0, max = 255, alpha = 100), 
        col.high = rgb(100,0,0, max = 255, alpha = 100)) 

par(font = 1)
text(-0.09,0.98,substitute(paste(bold("Pollinators"))),srt=90,xpd=NA )
text(-0.09,0.6,substitute(paste(bold("Plants"))),srt=90,xpd=NA )




### Sankey networks

library(networkD3)
library(tidyverse)


# I need a long format
data_long <- data.frame(jc_web) %>%
  rownames_to_column %>%
  gather(key = 'key', value = 'value', -rowname) %>%
  filter(value > 0)
colnames(data_long) <- c("source", "target", "value")
data_long$target <- paste(data_long$target, " ", sep="")


# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(name=c(as.character(data_long$source), as.character(data_long$target)) %>% unique())


# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
data_long$IDsource=match(data_long$source, nodes$name)-1 
data_long$IDtarget=match(data_long$target, nodes$name)-1

# prepare colour scale

# Make the Network
sankeyNetwork(Links = data_long, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=FALSE, nodeWidth=40, fontSize=13, nodePadding=2)




##### Another examples ####



library(gridGraphics)


# Creates a gTree object from the "usual" plot generated by `plotweb`
my_gTree <- grid.grabExpr(grid.echo(function() plotweb(Safariland)))
# View the structure of the newly created gTree object
View(my_gTree)

# Example of editing the font of the text grobs in the range 28-36, 
# that is, the bottom labels (use regular expression)
my_gTree <- editGrob(grob = my_gTree,
                     gPath = "graphics-plot-1-text-2[8-9]|3[0-6]", 
                     gp = gpar(font = 3L),
                     grep = TRUE,
                     global = TRUE)
# Plot the edited graph
grid.newpage(); grid.draw(my_gTree)


